class WorldParams:
    LIDAR_LIMIT = 300
    LIDAR_NOISE = 1
    CM_PER_PIXEL = 2.5
    ACCELERATE_PER_SECOND = 1
    MAX_SPEED = 0.5
    ROTATION_PER_SECOND = 60
    MIN_MOTION_ACCURACY = 0
    MAX_MOTION_ACCURACY = 1
    MIN_ROTATION_ACCURACY = 0
    MAX_ROTATION_ACCURACY = 1
